export const vacine = [
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AOT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "JANSS",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2020-W10",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 8,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "UNK",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2020-W10",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "MOD",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "AZ",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "NVXD",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 5333,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 61425,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "COM",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 1,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "COM",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "UNK",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "MOD",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "AZ",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "NVXD",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "JANSS",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "NVXD",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "AZ",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "JANSS",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "UNK",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "COM",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "MOD",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "NVXD",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 5,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "COM",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "UNK",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "AZ",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "JANSS",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "MOD",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "AZ",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "MOD",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "NVXD",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "JANSS",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 90,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "COM",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 1,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "UNK",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 5,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "UNK",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "AZ",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "JANSS",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 1327,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "COM",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "MOD",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "NVXD",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 2,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age50_59",
        "Vaccine": "UNK",
        "Denominator": 1399348
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 1050,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age50_59",
        "Vaccine": "COM",
        "Denominator": 1399348
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age50_59",
        "Vaccine": "MOD",
        "Denominator": 1399348
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age50_59",
        "Vaccine": "AZ",
        "Denominator": 1399348
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age50_59",
        "Vaccine": "NVXD",
        "Denominator": 1399348
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age50_59",
        "Vaccine": "JANSS",
        "Denominator": 1399348
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age5_9",
        "Vaccine": "UNK",
        "Denominator": 428300
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 1,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age5_9",
        "Vaccine": "COM",
        "Denominator": 428300
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age5_9",
        "Vaccine": "MOD",
        "Denominator": 428300
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age5_9",
        "Vaccine": "NVXD",
        "Denominator": 428300
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age5_9",
        "Vaccine": "JANSS",
        "Denominator": 428300
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age5_9",
        "Vaccine": "AZ",
        "Denominator": 428300
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age60_69",
        "Vaccine": "MOD",
        "Denominator": 1047888
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age60_69",
        "Vaccine": "AZ",
        "Denominator": 1047888
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age60_69",
        "Vaccine": "JANSS",
        "Denominator": 1047888
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 601,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age60_69",
        "Vaccine": "COM",
        "Denominator": 1047888
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age60_69",
        "Vaccine": "NVXD",
        "Denominator": 1047888
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age60_69",
        "Vaccine": "UNK",
        "Denominator": 1047888
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age70_79",
        "Vaccine": "MOD",
        "Denominator": 753524
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age70_79",
        "Vaccine": "AZ",
        "Denominator": 753524
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age70_79",
        "Vaccine": "NVXD",
        "Denominator": 753524
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age70_79",
        "Vaccine": "JANSS",
        "Denominator": 753524
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age70_79",
        "Vaccine": "UNK",
        "Denominator": 753524
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 564,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age70_79",
        "Vaccine": "COM",
        "Denominator": 753524
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age80+",
        "Vaccine": "AZ",
        "Denominator": 502105
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age80+",
        "Vaccine": "NVXD",
        "Denominator": 502105
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age80+",
        "Vaccine": "MOD",
        "Denominator": 502105
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 1701,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age80+",
        "Vaccine": "COM",
        "Denominator": 502105
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age80+",
        "Vaccine": "UNK",
        "Denominator": 502105
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age80+",
        "Vaccine": "JANSS",
        "Denominator": 502105
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age<18",
        "Vaccine": "AZ",
        "Denominator": 1543886
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 7,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age<18",
        "Vaccine": "COM",
        "Denominator": 1543886
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age<18",
        "Vaccine": "JANSS",
        "Denominator": 1543886
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age<18",
        "Vaccine": "UNK",
        "Denominator": 1543886
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age<18",
        "Vaccine": "MOD",
        "Denominator": 1543886
    },
    {
        "YearWeekISO": "2020-W53",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8901064",
        "ReportingCountry": "AT",
        "TargetGroup": "Age<18",
        "Vaccine": "NVXD",
        "Denominator": 1543886
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "JANSS",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "MOD",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 6,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "UNK",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "AZ",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "NVXD",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 26375,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 61425,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "ALL",
        "Vaccine": "COM",
        "Denominator": 7388778
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "MOD",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "COM",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "AZ",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "UNK",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "NVXD",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age0_4",
        "Vaccine": "JANSS",
        "Denominator": 433755
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "MOD",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "COM",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "JANSS",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "NVXD",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "UNK",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age10_14",
        "Vaccine": "AZ",
        "Denominator": 423433
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "MOD",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "AZ",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "JANSS",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 23,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "COM",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "NVXD",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age15_17",
        "Vaccine": "UNK",
        "Denominator": 258398
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "MOD",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "UNK",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "AZ",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "JANSS",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 796,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "COM",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age18_24",
        "Vaccine": "NVXD",
        "Denominator": 683584
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "AZ",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "MOD",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 1,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "UNK",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 10493,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "COM",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "JANSS",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age25_49",
        "Vaccine": "NVXD",
        "Denominator": 3002329
    },
    {
        "YearWeekISO": "2021-W01",
        "FirstDose": 0,
        "FirstDoseRefused": "",
        "SecondDose": 0,
        "DoseAdditional1": 0,
        "DoseAdditional2": 0,
        "UnknownDose": 0,
        "NumberDosesReceived": 0,
        "NumberDosesExported": 0,
        "Region": "AT",
        "Population": "8932664",
        "ReportingCountry": "AT",
        "TargetGroup": "Age50_59",
        "Vaccine": "MOD",
        "Denominator": 1399348
    },

]
